<div class="jumbotron" style="border-radius: 1.5%;text-align:center;margin-top:2%">
    <h1>Connectez-vous</h1>
        <form name="inscription" method="post" action="includes/adminlogin.php" style="font-size:1.1vw">
            <label for="pseudo" style="margin-left:-0.5vw">Pseudo : </label><br><input style="margin-top:0.4vw;margin-bottom:0.5vw;margin-left:-0.5vw"" type="text" name="username" required/> <br/>
            <label for="nom_de_passe" style="margin-left:-0.5vw">Mot de passe :</label><br><input style="margin-top:0.4vw;margin-left:-0.5vw" type="password" name="password" required
                                      /><br/>
            <input type="submit" class="btn btn-info" name="valider" value="Submit"
                   style="font-size:1.2vw;width:6vw;margin-left:-0.54vw;margin-top:1vw"/>
        </form>
</div>
