<div class="jumbotron">

    <form method="POST" action="includes/eventcheck.php">


        <div class="form-group">
            <label for="exampleFormControlInput1">Adresse Email</label>
            <input type="email" class="form-control" placeholder="example@example.com">
        </div>
        <div class="form-group">
            <label for="exampleFormControlSelect1">Code confidentiel</label>
            <input type="text" class="form-control">
        </div>
        <button type="submit" class="btn btn-primary mb-2" style="text-align:center">Voir evenement</button>


    </form>


</div>