<div class="jumbotron">




   <form action="includes/addusertoevent.php" method="post" enctype='multipart/form-data'>

        <div class="form-group">
            <input type="file" name="fileToUpload" id="fileToUpload">
            <br>
            <br>
            <input role="button" type="submit" name="submit" class="btn btn-primary btn-lg" value="Valider"
                   style="float:left;">

        </div>
    </form>
</div>