<div class="row" style="background-color: #F5F3F3; margin-top: 1%; margin-bottom: 1%; border-radius: 50px;">

<div class="col-md-4" style="border-right: 0.11vw solid #00B9E5;" id="fixResolution">

<h2 style="color: #00B9E5; text-align: right;"> BQM by AG2R</h2>

<div id="carousel_de_mots" class="carousel slide" data-ride="carousel" style="text-align: right;">
  <div class="carousel-inner" >
    <div class="carousel-item active" style="margin-left:4%">
        <img class="img-fluid" src="img/carroussel_1_2.png">
    </div>
    <div class="carousel-item" style="margin-left:4%">
      <img class="img-fluid" src="img/carroussel_2_2.png">
    </div>
    <div class="carousel-item" style="margin-left:4%">
      <img class="img-fluid" src="img/carroussel_3_2.png">
    </div>
	<div class="carousel-item" style="margin-left:4%">
      <img class="img-fluid" src="img/carroussel_4_2.png">
    </div>
  </div>
</div>


<br>

    <p class="lead" style="text-align: right;color:#030303">
	
	 AG2R La Mondiale est un organisme français, à but non lucratif, de protection sociale et patrimoniale. 
	Sa gouvernance repose sur le paritarisme et le mutualisme. 
        AG2R La Mondiale assure 15 millions de clients particuliers et 500 000 entreprises. </p>

    <p class="lead" style="text-align: right;color:#030303">
	En 2016, dans le classement réalisé par l’Argus de l’Assurance, AG2R La Mondiale occupe la première place des groupes de protection sociale et la deuxième place en assurance de personnes en France. 
    </p>
    <p class="lead" style="text-align: right;color:#030303">
        Le Business Quick Meeting d'AG2R LA MONDIALE est un concept pratique et efficace de rendez-vous informels destiné aux entreprises dynamiques désireuses de se développer dans une atmosphère conviviale. </p>
    <p class="lead" style="text-align: right;color:#030303">
		Pour les dirigeants d'entreprise, c'est l'occasion d'établir de nouveaux contacts pour développer leur réseau professionnel de clients, de fournisseurs et de partenaires.
        Une formule originale qui permet en 1 minute de briser la glace et d’échanger en toute convivialité sur les bonnes pratiques des uns et des autres. </p>


</div>

<div class="col-sm-4 col-md-8">

	

    <h2 id="eventTitle" style="color: #00B9E5; text-align: center;">Nos prochains évènements</h2>

</br>


 <center><p>Vous avez déjà un compte BQM ? Inscrivez-vous grâce à votre email et votre mot de passe !
	<br>
	Vous n'avez pas de compte BQM ? Créez un compte avant de vous inscrire à un évènement !</p> </center>

<br>


<div id="carousel_de_fiches" class="carousel slide" data-ride="carousel" style="text-align: center;">
  <div class="carousel-inner">

            <?php
            $selectQry = "SELECT * FROM events WHERE 1";
            $selectRes = mysqli_query($conn,$selectQry);
            $dumpCounter = 0;
            while ($selectRow = mysqli_fetch_row($selectRes)){
                if ($dumpCounter == 0)
                    echo "<div class=\"carousel-item active\">";
                else
                    echo "<div class=\"carousel-item\">";

                echo "<center><div class=\"card\" style=\"width: 15rem;height: 22rem\"><center><img class=\"img-fluid\" src=\"img/meeting.png\" class=\"card-img-top\" style=\"margin-top: 5%;\"></center>
                        <card-body>";
                foreach ($selectRow as $key => $value) {
                    if ($key == 1)
                        echo "<tr><input style=\"background-color:#e9ecef\" type=\"text\" class=\"jsName\" name=\"nom_{$dumpCounter}\" readonly value=\"{$value}\"></tr></br>";
                    else if ($key == 2)
                        echo "<tr><input style=\"background-color:#e9ecef\" type=\"text\" readonly value=\"{$value}\"></tr></br>";
                    else if ($key == 3)
                        echo "<tr><input style=\"background-color:#e9ecef\" type=\"text\" readonly value=\"{$value}\"></tr></br></br>";
                    else if ($key == 4) {
                        
                        echo "<tr><button class=\"btn btn-primary registerButtonsIndex\" name=\"submit_{$dumpCounter}\" style=\"text-align:center;\">Inscription</button></tr></br>";
                        $dumpCounter++;
                    }
                }
                echo "</card-body></div></center></div>";

            }
            ?>
      <script src="js/popup.js" type="text/javascript"></script>


</div>

</div>
<a class="carousel-control-prev" href="#carousel_de_fiches" data-slide="prev">
    <span class="carousel-control-prev-icon"></span>
  </a>
  <a class="carousel-control-next" href="#carousel_de_fiches" data-slide="next">
    <span class="carousel-control-next-icon"></span>
  </a>


	
</div>

</div>
</div>


<!--<script type="text/javascript">
var buttons = document.getElementsByClassName("inscription");
for(var i = 0; i < buttons.length ; i++){
    buttons[i].addEventListener("click", function() {
        Swal.fire({
            title: '?',
            text: "!",
            type: 'question',
            showCancelButton: true,
            confirmButtonColor: '#3085d6',
            cancelButtonColor: '#d33',
            confirmButtonText: 'Yes, delete it!'
        }).then((result) => {
            if (result.value) {
                Swal.fire(
                    'Deleted!',
                    'Your file has been deleted.',
                    'success'
                )
            }
        })
    });
}


</script> -->

<!-- 	<div class="table-responsive">
        <form action="eventregister.php" method="POST">
        <table class="table table-bordered table-condensed table-body-center">

            <thead style="background-color:rgba(22, 23, 25,0.2)">
            <th scope="col" style="width:25%;">Nom</th>
            <th scope="col" style="width:40%;">Location</th>
            <th scope="col" style="width:20%;">Heure Depart</th>
            <th scope="col" style="width:11%;text-align:center;">Nombre Participants</th>
            <th scope="col" style="text-align:center;">Inscription</th>
            </thead>

    
        <i class="fa fa-arrow-right" style="margin-left:95%;margin-top: -17%;font-size:2.6vw;"><a class="carousel-control-next" href="#carousel_de_fiches" data-slide="next"></a></i>
		
            <tbody> -->


