

<div class="jumbotron" style="margin-top: 1%; border-radius: 50px;">
    <form action="includes/userlogin.php" method="POST" enctype="multipart/form-data" style="
	line-height: 2;
	font-size: 20px;
	margin-right: 8%;
	margin-left: 8%;
	border: 0.12vw solid #00B9E5;
	border-radius: 1%;
	background-color: #F5F3F3;
	padding: 1%;"
>
        <div class="form-group">
            <label>Email</label>
            <input name="email" class="form-control" placeholder="Adresse Email" required>
        </div>
        <div class="form-group">
            <label>Mot de Passe</label>
            <input name="mdp" class="form-control" type="password" placeholder="Mot de Passe" required>
        </div>
        <center><button type="submit" class="btn btn-primary mb-2" style="text-align:center">Se connecter</button></center>
    </form>
</div>